config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :owner_profiles, only: [ :new, :create, :show, :edit, :update, :index]


  resources :jobs, only: [ :new, :create, :show, :edit, :update, :index] do
    resources :worker_profiles, only: [ :index ]
    resources :payments, only: [:new, :create]
  end

  match 'create_new_owner_profile', to: 'owner_profiles#create', via: :get

  match 'worker_jobs', to: 'jobs#my_worker_jobs', via: :get

  match 'store_worker_id', to: 'worker_profiles#store_worker_id', via: :post

  namespace :dashboard do
    get 'owners', to: "dashboards#owner"
    get 'workers', to: "dashboards#worker"
  end

  resources :worker_profiles, only: [ :new, :create, :show, :edit, :update, :index] do
    resources :jobs, only: [ ] do
     resources :requests, only: [ :new, :create, :index, :show]
    end
  end


  resources :requests, only: [ :edit, :create, :update, :show ]

end

app/models/job.rb
class Job < ApplicationRecord

  include PgSearch
  multisearchable against: [:category]

  belongs_to :owner_profile
  CATEGORIES = ["Painting", "Plumbing", "Electrics", "Carpentry", "Cleaning", "Handyman", "Other"]
  validates :category, inclusion: {in: CATEGORIES}
  # Added
  has_many :worker_profiles, through: :requests
  has_many :requests

  has_attachments :photos, maximum: 4

  def price
    requests.last.total_price.to_i
  end

  def price_cents
    price*100
  end


end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
skip_before_action :authenticate_user!, only: [:new, :create]
  def index
    if params["category"]
      @jobs_search = PgSearch.multisearch(params["category"].capitalize)
    else
      @jobs = Job.all
    end
  end

  def show
    @request = Request.new
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    cookies[:job_create] = job_params
    @job = Job.new(job_params)
    # @job.user = current_user
    # @owner_profile.user = current_user
    if !current_user.nil?
      @owner_profile = OwnerProfile.where(user_id: current_user.id).last
      @job.owner_profile = @owner_profile
      # raise
      @job.save
      redirect_to job_worker_profiles_path(job_id: @job.id, category: job_params[:category])
    else
      @job.save
      redirect_to job_worker_profiles_path(job_id: @job.id, category: job_params[:category])
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    @job.update(job_params)
    @job.save
    redirect_to owner_profile_jobs(@job)
  end


  private

  def job_params
      params.require(:job).permit(:title, :description, :category, photos: [])
    end

  def set_job
    @job = Job.find(params[:id])
  end


end

app/views/jobs/index.html.erb
This is the JOBS INDEX

<% if @jobs_search %>
  <ul>
    <% @jobs_search.each do |job| %>
    <li>
      <h2>
        <%= job.searchable.title %>
      </h2>
      <p>
        <%= job.searchable.description %>
      </p>
      <strong>
        <%= job.searchable.category %>
      </strong>

      </li>
    <% end %>
  </ul>

<% else %>
  <ul>
    <% @jobs.each do |job| %>
    <li>
      <h2>
        <%= job.title %>
      </h2>
      <p>
        <%= job.description %>
      </p>
      <strong>
        <%= job.category %>
      </strong>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/jobs/my_owner_jobs.html.erb
<% if current_user.owner_profile  %>
<p>Owner's Tasks: </p>
    <% current_user.owner_profile.jobs.each do |job| %>
    <p><%= link_to job_path(job) do %>
      <%=  job.title %>
      <%=  job.description %>
    </p>

    <% end %>
  <% end %>
<% end %>
<%= link_to "Owner dashboard", owner_profiles_path, style: "color: green" %>

app/views/jobs/my_worker_jobs.html.erb
<% if current_user.worker_profile %>
<p> Jobs for Workers: </p>
  <% current_user.worker_profile.jobs.each do |job| %>

    <p><%= link_to job_path(job) do %>
      <%=  job.title %>
      <%=  job.description %>
    </p>

    <% end %>
  <% end %>
<% end %>
<%= link_to "List of Workers", worker_profiles_path, style: "color: red" %>

app/views/jobs/new.html.erb
<div class="container bm">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-offset-4 col-md-4 text-center">
      <div class="form form-style">
        <h2>Create a new Job</h2>
        <%= simple_form_for @job do |f| %>
        <div class="form-inputs">

          <%= f.input :title, placeholder: "My boiler is broken and I am frozen!" %>
          <%= f.input :category, selected: params["category"], collection: Job::CATEGORIES %>
          <%= f.input :description, placeholder: "I need ..."  %>
          <%= f.hidden_field :status, value: "pending" %>
          <%= f.input :photos, as: :attachinary %>
        </div>
        <div class="form-actions">
          <%= f.submit "Publish your job", class: "btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<br>

app/views/jobs/show.html.erb
<div class="container bm">
  <div class="row">
    <div class="col-xs-9">
      <div class="requests-display">
        <div class="requests-header">
          <h2><%= @job.title %></h2>
        </div>
        <% @job.requests.each do |request| %>
        <div class="requests-box">
          <p>Description Worker:</p>
          <p><%= request.worker_profile.skill_area %></p>
          <p><%= request.worker_profile.bio %></p>
          <% if request.status == Request::QUOTE_SENT %>
            <p>Total Price: <%= request.total_price %>€</p>
          <% end %>
        </div>
        <% end %>
        <div class="requests-box-1">
          <h3><b>Description Job:</b></h3>
          <p><strong>Category:</strong> <%= @job.category %></p>
          <p><strong>Status:</strong> <%= @job.status %></p>
          <p><%= @job.description %></p>
          <p> Creation date: <%= @job.created_at %></p>
        </div>
        <div>
          <% @job.photos.each do |photo| %>
            <%= cl_image_tag photo.path, width: 300, height: 200, crop: :fill %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-xs-3 request-side">
      <p><%= link_to "Back to Dashboard", worker_profiles_path %></p>
        <%#= simple_form_for @job.requests.where(status: "accepted").last do |f| %>
          <%#= f.hidden_field :status, value: "Confirm" %>
          <%#= f.submit "Confirm", new_job_payment_path(@job), class: "btn btn-primary" %>
        <%# end %>
      <%= link_to "Accept", new_job_payment_path(@job), class: "btn-medium btn-sm" %>
      <%= link_to "Reject", root_path, class: "btn-medium-red btn-sm" %>
    </div>
  </div>
</div>


<p><%= link_to "Go to User Dashboard", owner_profiles_path %></p>