config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :owner_profiles, only: [ :new, :create, :show, :edit, :update, :index]


  resources :jobs, only: [ :new, :create, :show, :edit, :update, :index] do
    resources :worker_profiles, only: [ :index ]
    resources :payments, only: [:new, :create]
  end

  match 'create_new_owner_profile', to: 'owner_profiles#create', via: :get

  match 'worker_jobs', to: 'jobs#my_worker_jobs', via: :get

  match 'store_worker_id', to: 'worker_profiles#store_worker_id', via: :post

  namespace :dashboard do
    get 'owners', to: "dashboards#owner"
    get 'workers', to: "dashboards#worker"
  end

  resources :worker_profiles, only: [ :new, :create, :show, :edit, :update, :index] do
    resources :jobs, only: [ ] do
     resources :requests, only: [ :new, :create, :index, :show]
    end
  end


  resources :requests, only: [ :edit, :create, :update, :show ]

end

app/views/shared/_avatar.html.erb
<% if current_user %>
  <img src="<%= cl_image_path current_user.photo, height: 100, width: 100, crop: :thumb, gravity: :face if current_user.photo? %>" class="avatar-large">
<% end %>

app/views/shared/_browse_dropdown.html.erb
<ul class="dropdown-menu navbar-wagon-dropdown-menu">
  <li>
    <%= link_to "#" do %>
    <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
    <% end %>
  </li>
  <li>
    <%= link_to "#" do %>
    <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
    <% end %>
  </li>
  <% if !current_user.nil? %>
    <% if current_user.is_owner? %>
        <li>
          <%= link_to  jobs_path do %>
          <i class="fa fa-dashboard"></i> Owner dashboard
          <% end %>
        </li>
        <% end %>
        <% if current_user.is_worker? %>
        <li>
          <%= link_to dashboard_workers_path do %>
          <i class="fa fa-dashboard"></i> Worker dashboard
          <% end %>
        </li>
        <% end %>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
  <% end  %>
</ul>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="left">
    <ul class="footer-link-menu">
      <li>LOCATIONS</li>
      <li> </li>
      <li><a href="#">Barcelona</a></li>
      <li><a href="#">Madrid</a></li>
      <li><a href="#">Valencia</a></li>
      <li><a href="#">Alicante</a></li>
      <li><a href="#">Malaga</a></li>
    </ul>
    <ul class="footer-link-menu">
      <li>POPULAR SERVICES</li>
      <li><a href="#">Painting</a></li>
      <li><a href="#">Plumbing</a></li>
      <li><a href="#">Electrics</a></li>
      <li><a href="#">Carpentry</a></li>
      <li><a href="#">Cleaning</a></li>
      <li><a href="#">Handyman</a></li>
      <li><a href="#"></a></li>
    </ul>
  </div>
  <div class="right footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navatar.html.erb
<% if current_user %>
  <% if current_user.photo?  %>
      <div class="avatar-wrapper dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown" >
    <img src="<%= cl_image_path current_user.photo, height: 30, width: 30, crop: :thumb, gravity: :face %>", class= "avatar" >
  </div>
    <% else %>
    <div class="avatar-wrapper dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown" >
      <i class="avatar-icon fa fa-user-o" aria-hidden="true"></i>
    </div>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="nav-wrap">
  <div class="container">
    <div class="row">
      <div class="navbar-wagon">
        <!-- Logo -->
        <!-- can't click on logo, just at the corners of logo  -->
        <%= link_to root_path, class: "navbar-wagon-brand" do %>
        <%= image_tag 'logo-ddiy-7.png', style: "height: 30px; border-radius: 50%" %>
        <% end %>

        <!-- Right Navigation -->
        <div class="navbar-nav">
          <% if user_signed_in? %>
          <!-- Links when logged in -->
          <% if current_user && current_user.owner_profile && current_user.worker_profile %>
          <%= link_to "Create Job", new_job_path, class: "navbar-wagon-item navbar-wagon-link nav-item" %>
          <%= link_to "My worker jobs", worker_profiles_path, class: "navbar-wagon-item navbar-wagon-link nav-item" %>

          <% elsif current_user && current_user.worker_profile %>
          <%= link_to "My worker jobs", worker_profiles_path, class: "navbar-wagon-item navbar-wagon-link nav-item" %>
          <%= link_to "Worker dashboard", dashboard_workers_path, class: "navbar-wagon-item navbar-wagon-link nav-item" %>

          <% elsif current_user && current_user.owner_profile%>
          <%= link_to "Create Job", new_job_path, class: "navbar-wagon-item navbar-wagon-link nav-item" %>
          <%= link_to "Owner dashboard", dashboard_owners_path, class: "navbar-wagon-item navbar-wagon-link nav-item" %>

          <%= link_to "BECOME A PRO", new_worker_profile_path, class: "navbar-wagon-item navbar-wagon-link nav-item" %>

          <% elsif current_user %>
          <%= link_to "BROWSE", jobs_path, class: "navbar-wagon-item navbar-wagon-link nav-item" %>
          <%= link_to "HOW IT WORKS", root_path(:anchor => "how-it-works"), class: "navbar-wagon-item navbar-wagon-link nav-item" %>

          <% else %>
          <!-- PERHAPS SOMETHING IN THE FUTURE FR LOGIN -->
          <% end %>

              <!-- Links when logged in -->
            </div>

            <div class="navbar-wagon-right hidden-xs">

              <!-- Avatar with dropdown menu -->

              <form class="navbar-form hidden-sm">
                <div class="form-group">
                  <input type="text" class="form-control input-sm" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default input-sm"><i class="fa fa-search" aria-hidden="true"></i></button>
              </form>
              <i class="fa fa-question fa-lg" aria-hidden="true" style="padding-right: 15px;"></i>
              <i class="fa fa-bell" aria-hidden="true"></i>
              <div class="navbar-wagon-item">
                <div class="dropdown">
                  <%= render 'shared/navatar' %>
                  <%= render "shared/navbar_dropdown" %>
                </div>
              </div>
              <% else %>
            </div>

            <div class="navbar-nav hidden-xs">
              <!-- Links when logged in -->
              <%= link_to "BROWSE", jobs_path, class: "navbar-wagon-item navbar-wagon-link nav-item" %>
              <%= link_to "HOW IT WORKS", root_path(:anchor => "how-it-works"), class: "navbar-wagon-item navbar-wagon-link nav-item" %>

            </div>
            <div class="navbar-wagon-right hidden-xs hidden-sm">
              <!-- Login link (when logged out) -->
              <%= link_to t(".sign_in", default: "LOGIN"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link nav-item" %>
              <%= link_to t(".sign_in", default: "SIGN UP"), new_user_registration_path(user_type: :owner), class: "navbar-wagon-item navbar-wagon-link nav-item" %>
              <%= link_to t(".sign_in", default: "BECOME A PRO"), new_user_registration_path(user_type: :pro), class: "btn-medium btn-sm nav-item" %>

            </div>
            <% end %>
          </div>

          <!-- Dropdown list appearing on mobile only -->
          <div class="navbar-wagon-item hidden-sm hidden-md hidden-lg">
            <div class="dropdown">
              <%= render 'shared/navatar' %>
              <%= render "shared/navbar_dropdown" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_navbar_dropdown.html.erb
<ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu nbdds">
  <% if current_user && current_user.owner_profile && current_user.worker_profile %>
   <li><%= link_to dashboard_owners_path do %>
      <i class="fa fa-dashboard"></i> Owner dashboard
      <% end %></li>
  <li><%= link_to dashboard_workers_path do %>
    <i class="fa fa-wrench"></i> Worker dashboard
    <% end %></li>
  <li><%= link_to edit_owner_profile_path(current_user.owner_profile) do %><i class="fa fa-pencil-square-o"></i> Edit Owner Profile<% end %></li>
  <li><%= link_to edit_worker_profile_path(current_user.worker_profile) do %><i class="fa fa-pencil"></i> Edit Worker Profile<% end %></li>

  <% elsif current_user && current_user.worker_profile %>

    <li><%= link_to "Create Owner profile", new_owner_profile_path %></li>
    <li><%= link_to "Edit Worker profile", edit_worker_profile_path(current_user.worker_profile) %></li>

    <% elsif current_user && current_user.owner_profile%>
    <li><%= link_to new_job_path do %><i class="fa fa-paint-brush" aria-hidden="true"></i> Create Job<% end %></li>

      <li><%= link_to new_worker_profile_path do %><i class="fa fa-wrench"></i> Create Worker profile<% end %></li>
      <li><%= link_to edit_owner_profile_path(current_user.owner_profile) do %><i class="fa fa-pencil-square-o"></i> Edit Owner Profile<% end %></li>

      <% elsif current_user %>
      <li><%= link_to new_worker_profile_path do %><i class="fa fa-wrench"></i> Create Worker profile<% end %></li>
      <li><%= link_to new_owner_profile_path do %><i class="fa fa-home" aria-hidden="true"></i> Create Owner profile<% end %></li>

      <% else %>
      <!-- PERHAPS SOMETHING IN THE FUTURE FR LOGIN -->
      <% end %>
      <li>
        <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
        <% end %>
      </li>

    </ul>