config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :owner_profiles, only: [ :new, :create, :show, :edit, :update, :index]


  resources :jobs, only: [ :new, :create, :show, :edit, :update, :index] do
    resources :worker_profiles, only: [ :index ]
    resources :payments, only: [:new, :create]
  end

  match 'create_new_owner_profile', to: 'owner_profiles#create', via: :get

  match 'worker_jobs', to: 'jobs#my_worker_jobs', via: :get

  match 'store_worker_id', to: 'worker_profiles#store_worker_id', via: :post

  namespace :dashboard do
    get 'owners', to: "dashboards#owner"
    get 'workers', to: "dashboards#worker"
  end

  resources :worker_profiles, only: [ :new, :create, :show, :edit, :update, :index] do
    resources :jobs, only: [ ] do
     resources :requests, only: [ :new, :create, :index, :show]
    end
  end


  resources :requests, only: [ :edit, :create, :update, :show ]

end

app/controllers/dashboard/dashboards_controller.rb
class Dashboard::DashboardsController < ApplicationController
  def worker
    @user = current_user
    # @job_id = @user.worker_profile.user_id
    if @user.worker_profile.nil?
      redirect_to new_worker_profile_path
    else
      @worker_profile = WorkerProfile.find(@user.worker_profile.id)
    end

    # @request = Request.all.where(worker_profile_id: @worker_profile.id)[0]
    if params["status"] == "accepted"
        @requests = Request.where(worker_profile_id: @worker_profile.id, status: "accepted")
    elsif params["status"] == "send quote"
        @requests = Request.where(worker_profile_id: @worker_profile.id, status: "send quote")
    elsif params["status"] == "completed"
        @requests = Request.where(worker_profile_id: @worker_profile.id, status: "completed")
    elsif params["status"] == "expired"
        @requests = Request.where(worker_profile_id: @worker_profile.id, status: "expired")
    elsif params["status"] == "all"
      @requests = Request.where(worker_profile_id: @worker_profile.id)
    else
      @requests = Request.where(worker_profile_id: @worker_profile.id, status: "Pending")
    end

    if @request.nil?
    else
      @request = Request.find(worker_profile_id = "#{@worker_profile.id}")
    # @job = Job.all.where(id: @request.job_id)
      @job = Job.find("#{@request.job_id}")
    end

    # raise
  end

  def owner
    @user = current_user
    @owner_profile = OwnerProfile.find_by(user_id: @user.id)
    # @owner_profile = OwnerProfile.find("#{@user.owner_profile.id}")
    # @request = Request.all.where(owner_profile_id: @owner_profile.id)[0]
    # use it insteadof Requests.joins(:job).where(job: {owner_profile_id: @owner_profile.id, status: ...})

    if params["status"] == "recieved quote"
      @jobs = Job.where(owner_profile_id: @owner_profile.id, status: "recieved quote")
      # @requests = Requests.joins(:job).where(job: {owner_profile_id: @owner_profile.id, status: "recieved quote"})

    elsif params["status"] == "accepted"
      # @requests = Requests.joins(:job).where(job: {owner_profile_id: @owner_profile.id, status: "recieved quote"})
      @jobs = Job.where(owner_profile_id: @owner_profile.id, status: "accepted")
    elsif params["status"] == "completed"
      @jobs = Job.where(owner_profile_id: @owner_profile.id, status: "completed")
    elsif params["status"] == "declined"
      @jobs = Job.where(owner_profile_id: @owner_profile.id, status: "declined")
    elsif params["status"] == "all"
      @jobs = Job.where(owner_profile_id: @owner_profile.id)
    else
      @jobs = Job.where(owner_profile_id: @owner_profile.id, status: "pending")
    end

    if params["category"] == "Plumbing"
      @jobs = Job.where(owner_profile_id: @owner_profile.id, category: "Plumbing")
    elsif params["category"] == "Painting"
      @jobs = Job.where(owner_profile_id: @owner_profile.id, category: "Painting")
    end

    if @request.nil?
    else
      # @request = Request.find(owner_profile_id = "#{@owner_profile.id}")
    # @job = Job.all.where(id: @request.job_id)
      @job = Job.find("#{@request.job_id}")
    end

  end
end

app/views/dashboard/dashboards/owner.html.erb
<div class="container bm" style="margin-top: 30px">
  <div class="row">
    <div class="col-sm-2 hidden-xs" style="margin-top: 50px">
      <div class="status">
        <h4>Status</h4>
        <ul>
          <li class="status-<%= params[:status] == "all" ? "active" : "inactive" %>">
            <%= link_to "All Jobs", dashboard_owners_path(status: "all"), class: "" %>
          </li>

          <li class="status-<%= (params[:status] == nil || params[:status] == "pending") ? "active" : "inactive" %>">
            <%=  link_to "Pending", dashboard_owners_path(status: "pending"), class: "" %>
          </li>
          <li class="status-<%= (params[:status] == "send quote") ? "active" : "inactive" %>">
            <%= link_to "Received Quotes", dashboard_owners_path(status: "send quote"), class: "" %>
          </li>
          <li class="status-<%= (params[:status] == "accepted") ? "active" : "inactive" %>">
            <%= link_to "Accepted", dashboard_owners_path(status: "accepted"), class: "" %>
          </li>
          <li class="status-<%= (params[:status] == "completed") ? "active" : "inactive" %>">
            <%= link_to "Completed", dashboard_owners_path(status: "completed"), class: "" %>
          </li>
          <!-- Here also show requests: Canceled -->
          <li class="status-<%= (params[:status] == "declined") ? "active" : "inactive" %>">
            <%= link_to "Declined", dashboard_owners_path(status: "declined"), class: "" %>
          </li>
        </ul>
      </div>
      <div class="status">
        <h4>Categories</h4>
        <ul>
          <li class="status-<%= params[:category] == "Plumbing" ? "active" : "inactive" %>">
            <%= link_to "Plumber", dashboard_owners_path(category: "Plumbing"), class: "" %>
          </li>
          <li class="status-<%= params[:category] == "Electrics" ? "active" : "inactive" %>">
            <%= link_to "Electrician", dashboard_owners_path(category: "Electrics"), class: "" %>
          </li>
          <li class="status-<%= params[:category] == "Carpentry" ? "active" : "inactive" %>">
            <%= link_to "Carpenter", dashboard_owners_path(category: "Carpentry"), class: "" %>
          </li>
          <li class="status-<%= params[:category] == "Painting" ? "active" : "inactive" %>">
            <%= link_to "Painter", dashboard_owners_path(category: "Painting"), class: "" %>
          </li>
          <li class="status-<%= params[:category] == "Cleaning" ? "active" : "inactive" %>">
            <%= link_to "Cleaner", dashboard_owners_path(category: "Cleaning"), class: "" %>
          </li>
          <li class="status-<%= params[:category] == "Handyman" ? "active" : "inactive" %>">
            <%= link_to "Handyman", dashboard_owners_path(category: "Handyman"), class: "" %>
          </li>
          <li class="status-<%= params[:category] == "Other" ? "active" : "inactive" %>">
            <%= link_to "Other", dashboard_owners_path(category: "Other"), class: "" %>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-sm-7">
      <div class="card-list">
        <h2>My Jobs</h2>
      </div>
      <% if @jobs.empty? %>
      <p><%=  "You have no jobs at the moment. Don't do it yourself. Local professionals compete for your jobs." %></p>
      <%= link_to "Create your first job now!", new_job_path %>
      <%else%>
      <% @jobs.each do |job| %>
      <div class="card">
        <div class="card-main">
          <% if job.photos.first %>
          <div class="card-user">
            <img src="<%= cl_image_path job.photos.first.path %>", height=50 >
          </div>
          <% end %>
          <div class="card-title">
            <h2><%= job.title %></h2>
          </div>
          <div class="card-details">
            <p><%= current_user.email %> Estimated time: 4 hours - Posted 57 minutes ago</p>
          </div>
          <div class="card-description">
            <p><%= job.description %></p>
          </div>
          <div class="card-payment">Client Payment: Verified
          </div>
          <div class="card-location">
            <p><i class="fa fa-map-marker" aria-hidden="true"></i> <%= current_user.location %></p>
          </div>
        </div>
        <div class="card-side">
          <p class="status pending"><%= job.status %></p>
          <p class="price">50 $ / hour</p>
        </div>

        <%= link_to "", job_path(job.id), class: "card-link" %>
      </div>

      <% end %>
      <% end %>
    </div>
    <div class="col-sm-3 hidden-xs" style="margin-top: 50px">
      <div class="myprofile">
        <div class="myprofile-header">
          <% if current_user.photo?  %>
          <img src="<%= cl_image_path current_user.photo, height: 30, width: 30, crop: :thumb, gravity: :face %>", class="avatar"  >
          <% else %>
          <div class="avatar">
            <i class="avatar-icon fa fa-user-o" aria-hidden="true"></i>
            <% end %>
          </div>
          <%= link_to "My Profile", owner_profile_path(current_user.owner_profile), class: "" %>

          <div class="myprofile-visibility">
            <h3>Visibility</h3>
            <i class="fa fa-globe" aria-hidden="true"></i><a>Public</a>
          </div>
          <div class="myprofile-availibility">
            <h3>Availibility</h3>
            <a>08:00 - 20:00</a>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/dashboards/worker.html.erb
<div class="container bm" style="margin-top: 30px">
  <div class="row">
    <div class="col-sm-2 hidden-xs" style="margin-top: 50px">
      <div class="status">
        <h4>Status</h4>
        <ul>
          <li class="status-<%= (params[:status] == nil || params[:status] == "Pending") ? "active" : "inactive" %>">
            <%= link_to "Pending", dashboard_workers_path(status: "Pending"), class: "" %>
          </li>

          <li class="status-<%= params[:status] == "send quote" ? "active" : "inactive" %>">
            <%= link_to "Send Quote", dashboard_workers_path(status: "send quote"), class: "" %>
          </li>
          <li class="status-<%= params[:status] == "accepted" ? "active" : "inactive" %>">
            <%= link_to "Accepted", dashboard_workers_path(status: "accepted"), class: "" %>
          </li>
          <li class="status-<%= params[:status] == "completed" ? "active" : "inactive" %>">
            <%= link_to "Completed", dashboard_workers_path(status: "completed"), class: "" %>
          </li>
          <li class="status-<%= params[:status] == "expired" ? "active" : "inactive" %>">
            <%= link_to "Expired", dashboard_workers_path(status: "expired"), class: "" %>
          </li>
          <li class="status-<%= params[:status] == "all" ? "active" : "inactive" %>">
            <%= link_to "All Requests", dashboard_workers_path(status: "all")%>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-sm-7">
      <div class="card-list">
        <h2>My Job Requests</h2>
      </div>
      <div class="card">
        <% if @job.nil? && @requests.blank? %>
        <div class="card">
          <div class="card-main">
            <div class="card-title">
              <p><%=  "You have no requests at the moment" %></p>
              <%=  "Refresh in a minute or check again later" %>
            </div>
          </div>
        </div>
        <%else%>
        <% @requests.each do |request| %>
        <div class="card">
          <div class="card-main">
            <!-- <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay"> -->
            <div class="card-user">
              <% if image_tag request.worker_profile.user.photo.url(:bright_face).nil? %>
              <img src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
              <% else %>
              <%= image_tag request.worker_profile.user.photo.url(:bright_face) %>
              <% end %>
            </div>
            <div class="card-title">
              <h3><%= request.job.title %></h3>
            </div>
            <div class="card-description">
              <p><%= request.job.description %></p>
            </div>
            <div class="card-payment">Client Payment: Verified
            </div>
            <div class="card-location">
              <p><i class="fa fa-map-marker" aria-hidden="true"></i> Barcelona, España</p>
            </div>
          </div>
          <div class="card-side">
            <p class="status pending"><%= request.status %></p>
            <p class="price"><%= request.worker_profile.price_per_hour %> $ / hour</p>
            <div class="row">
              <%= simple_form_for request do |f| %>
              <%= f.hidden_field :status, value: "accepted" %>
              <%= f.submit "respond", class: "btn btn-primary" %>
              <% end %>
              <%= simple_form_for request do |f| %>
              <%= f.hidden_field :status, value: "cancelled" %>
              <% link_to dashboard_workers_path %>
              <%= f.submit "decline", class: "btn btn-primary" %>
              <% end %>
            </div>

            <%= link_to '', worker_profile_job_request_path(@worker_profile, request.job, request.id), class: "card-link" %>
            <!-- may be delete this div -->
          </div>


          <div class="card-title">
            <h3><%= request.job.title %></h3>
          </div>
          <div class="card-description">
            <p><%= request.job.description %></p>
          </div>
          <div class="card-payment">Client Payment: Verified
          </div>
          <div class="card-location">
            <p><i class="fa fa-map-marker" aria-hidden="true"></i> Barcelona, España</p>
          </div>
        </div>
        <div class="card-side">
          <%= link_to '', worker_profile_job_request_path(@worker_profile, request.job, request.id), class: "card-link" %>
          <!-- may be delete this div -->
        </div>
      </div>

      <% end %>
      <% end %>
    </div>
  </div>
  <div class="col-sm-3 hidden-xs" style="margin-top: 50px">
    <div class="myprofile">
      <div class="myprofile-header">
        <% if current_user.photo?  %>
        <img src="<%= cl_image_path current_user.photo, height: 30, width: 30, crop: :thumb, gravity: :face %>" class="avatar" >
        <% else %>
        <div class="avatar">
          <i class="avatar-icon fa fa-user-o" aria-hidden="true"></i>
        </div>
        <% end %>
        <%= link_to "My Profile", worker_profile_path(current_user.worker_profile), class: "" %>
      </div>
      <div class="myprofile-visibility">
        <h3>Visibility</h3>
        <i class="fa fa-globe" aria-hidden="true"></i><a>Public</a>
      </div>
      <div class="myprofile-availibility">
        <h3>Availibility</h3>
        <a>08:00 - 20:00</a>
      </div>
    </div>

  </div>
</div>