config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :owner_profiles, only: [ :new, :create, :show, :edit, :update, :index]


  resources :jobs, only: [ :new, :create, :show, :edit, :update, :index] do
    resources :worker_profiles, only: [ :index ]
    resources :payments, only: [:new, :create]
  end

  match 'create_new_owner_profile', to: 'owner_profiles#create', via: :get

  match 'worker_jobs', to: 'jobs#my_worker_jobs', via: :get

  match 'store_worker_id', to: 'worker_profiles#store_worker_id', via: :post

  namespace :dashboard do
    get 'owners', to: "dashboards#owner"
    get 'workers', to: "dashboards#worker"
  end

  resources :worker_profiles, only: [ :new, :create, :show, :edit, :update, :index] do
    resources :jobs, only: [ ] do
     resources :requests, only: [ :new, :create, :index, :show]
    end
  end


  resources :requests, only: [ :edit, :create, :update, :show ]

end

app/models/worker_profile.rb
class WorkerProfile < ApplicationRecord
  belongs_to :user
  validates :user_id, uniqueness: true
  SKILL_AREA = ["Painting", "Plumbing", "Electrics", "Carpentry", "Cleaning", "Handyman", "Other"]
  validates :skill_area, inclusion: {in: SKILL_AREA}
   # Added
  has_many :jobs, through: :requests
  has_many :requests

  accepts_nested_attributes_for :user

end

app/controllers/worker_profiles_controller.rb
class WorkerProfilesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :new, :show, :create, :store_worker_id]
  def index
    if params["category"]
      @worker_profiles = WorkerProfile.where(skill_area: params["category"])
    else
      @worker_profiles = WorkerProfile.all
    end
    if !current_user.nil?
      @job = Job.find_by_owner_profile_id(current_user.owner_profile.id)
    end
    if params["status"] == "all_pro"
      @worker_profiles = WorkerProfile.all
    end
  end

  def show
    # @request = Request.new
    @worker_profile = current_user.worker_profile || WorkerProfile.find(params[:id])
    @request = Request.new
    if params[:job_id]
      @job = Job.find(params[:job_id])
    end
  end

  def new
    @worker_profile = WorkerProfile.new
    @user = current_user
  end

  def store_worker_id
    if current_user.blank?
    cookies[:worker_id] = params["worker_profile_id"]
    redirect_to new_user_registration_path
    else
      # job_id: current_user. jobs
      @request = Request.new(job_id: params[:job_id], worker_profile_id: params[:worker_profile_id])
      if @request.save!
        flash[:notice] = "All good"
        redirect_to owner_profiles_path
      else
        flash[:alert] = "Something went wrong"
        render :new
      end
      redirect_to dashboard_owners_path
    end
  end

  def create
    @worker_profile = WorkerProfile.new(worker_params)
    @worker_profile.user = current_user
    current_user.update(user_params)
    if @worker_profile.save
      redirect_to dashboard_workers_path
    else
      render :new
    end
  end

  def edit
    set_worker_profile
  end

  def update
    set_worker_profile
    if current_user.worker_profile.update(worker_params) && current_user.update(user_params)
        redirect_to worker_profile_path(current_user)
    else
      render :new
    end
  end

  private

    def worker_params
      params.require(:worker_profile).permit(:verification_status, :skill_area, :price_per_hour, :bio, :available, :timetable, user: [:photo, :photo_cache, :first_name, :last_name, :location])
    end

    def user_params
       params.require(:user).permit(:photo, :photo_cache, :first_name, :last_name, :location)
    end

    def set_worker_profile
        @worker_profile = WorkerProfile.find(params[:id])
    end
end

app/views/worker_profiles/edit.html.erb
<div class="container bm">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3">
      <div class="form form-style">
        <h2>Edit your DDIY Pro profile</h2>
        <div class="editar">
          <%= render 'shared/avatar' %>
        </div>
        <%= simple_form_for @worker_profile do |f| %>
        <div class="form-inputs">

          <%= simple_form_for @worker_profile do |f| %>

          <%= f.input :skill_area, :collection => ["Builder", "Painter", "Carpenter", "Electrician", "Cleaner", "Handyman", "Other"], prompt: "Select your area of expertise" %>
          <%= f.input :price_per_hour, placeholder: "50€ per hour"  %>
          <%= f.input :bio, placeholder: "You don't see any paintbrush lines in my work!"  %>

          <%= simple_fields_for current_user do |f| %>
          <%= f.input :first_name %>
          <%= f.input :last_name %>
          <%= f.input :location %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <% end %>

          <div class="form-actions">
            <%= f.submit "Update your profile", class: "btn btn-primary" %>
          </div>
          <% end %>


          <div class="col-md-6 col-xs-12">

          </div>
          <div class="col-md-6 col-xs-12">

          </div>
          <div class="col-xs-12">

          </div>

        </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/worker_profiles/index.html.erb
<div class="container request-list" style="margin-top: 30px">
  <div class="row">
    <div class="hidden-xs col-sm-2" style="margin-top: 50px">

      <div class="status">
        <h4>Categories</h4>
        <ul>
          <li class="status-<%= (params[:category] == nil || params[:category] == "All pro") ? "active" : "inactive" %>">
             <%= link_to "All Pro", job_worker_profiles_path(@job), class: "" %>
          </li>
          <li class="status-<%= params[:category] == "Plumbing" ? "active" : "inactive" %>">
            <%= link_to "Plumber", job_worker_profiles_path(@job, category: "Plumbing"), class: "" %>
          </li>
          <li class="status-<%= params[:category] == "Electrics" ? "active" : "inactive" %>">
            <%= link_to "Electrician", job_worker_profiles_path(@job, category: "Electrics"), class: "" %>
          </li>
          <li class="status-<%= params[:category] == "Carpentry" ? "active" : "inactive" %>">
            <%= link_to "Carpenter", job_worker_profiles_path(@job, category: "Carpentry"), class: "" %>
          </li>
          <li class="status-<%= params[:category] == "Painting" ? "active" : "inactive" %>">
            <%= link_to "Painter", job_worker_profiles_path(@job, category: "Painting"), class: "" %>
          </li>
           <li class="status-<%= params[:category] == "Cleaning" ? "active" : "inactive" %>">
            <%= link_to "Cleaner", job_worker_profiles_path(@job, category: "Cleaning"), class: "" %>
          </li>
          <li class="status-<%= params[:category] == "Handyman" ? "active" : "inactive" %>">
            <%= link_to "Handyman", job_worker_profiles_path(@job, category: "Handyman"), class: "" %>
          </li>
          <li class="status-<%= params[:category] == "Other" ? "active" : "inactive" %>">
            <%= link_to "Other", job_worker_profiles_path(@job, category: "Other"), class: "" %>
          </li>
        </ul>
      </div>
    </div>


    <div class="col-xs-12 col-sm-10">
      <div class="card-list">
          <h2>Available Workers</h2>
      </div>

      <% @worker_profiles.each do |worker_profile| %>
      <div class="card">
        <div class="card-main">
          <div class="card-user">

              <% if worker_profile.user.photo?  %>
                <img src="<%= cl_image_path worker_profile.user.photo, height: 30, width: 30, crop: :thumb, gravity: :face %>" >
                <% else %>
                <div class="avatar-wrapper dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown" >
                  hello
                </div>
            <% end %>

          </div>
          <div class="card-title">
            <h2> <%= worker_profile.user.first_name %>
            <%= worker_profile.user.last_name %></h2>
          </div>
          <div class="card-details">
            <p><%= worker_profile.skill_area %></p>
          </div>
          <div class="card-description">
            <p><%= worker_profile.bio %></p>
          </div>
          <div class="card-payment">Client Payment: Verified
          </div>
          <div class="card-location">
            <p><i class="fa fa-map-marker" aria-hidden="true"></i> <%= worker_profile.user.location %></p>
          </div>
        </div>
        <div class="card-side">
          <p class="price card-sider"> Price per hour: <%= worker_profile.price_per_hour %></p>
          <p class="card-sider"><%= link_to "Choose Pro", worker_profile_path(worker_profile, job_id: params[:job_id]), class: "btn btn-primary input-sm" %></p>
        </div>
      </div>
      <%end %>
    </div>
  </div>
</div>

app/views/worker_profiles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="form form-style">
        <h2>Become a DDIY Pro</h2>
        <%= simple_form_for @worker_profile do |f| %>
        <div class="form-inputs">

          <%= simple_form_for @worker_profile do |f| %>

          <%= f.input :skill_area, collection: ["Painting", "Plumbing", "Electrics", "Carpentry", "Cleaning", "Handyman", "Other"], prompt: "Select your area of expertise" %>
          <%= f.input :price_per_hour, placeholder: "50€ per hour"  %>
          <%= f.input :bio, placeholder: "You don't see any paintbrush lines in my work!"  %>

          <%= simple_fields_for current_user do |f| %>
          <%= f.input :first_name %>
          <%= f.input :last_name %>
          <%= f.input :location %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <% end %>

          <div class="form-actions">
            <%= f.submit "Get started", class: "btn btn-primary" %>
          </div>
          <% end %>

        </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/worker_profiles/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-9">
      <div class="requests-display">
        <div class="requests-header">
          <h2><p>Worker Profile</p></h2>
        </div>
        <div class="requests-box">
          <div class="request-top">
            <div class="request-top-left">
              <p> Skill area: <%= @worker_profile.skill_area %></p>
              <p> Description: <%= @worker_profile.bio %></p>
              <!-- <p> Price per hour: €<%= @worker_profile.price_per_hour %></p> -->

            </div>
            <div class="request-top-right">
              <p> Available: <%= @worker_profile.available %></p>
              <p> Completed Tasks: 5 <%= @worker_profile.completed_tasks %></p>
              <p> Rating: <%= @worker_profile.rating %></p>
            </div>
            <div class="avatar-div">

              <% if @worker_profile.user.photo?  %>
                <img src="<%= cl_image_path @worker_profile.user.photo, height: 30, width: 30, crop: :thumb, gravity: :face %>" >
                <% else %>
                <div class="avatar-wrapper dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown" >

                </div>
            <% end %>

            </div>

          </div>

          <div class="request-mid">
            <h3>Description</h3>
            <p><%= @worker_profile.bio %></p>

                    <%#= button_to "Select this profile", store_worker_id_path(worker_profile_id: @worker_profile.id), class: "btn btn-primary input-sm" %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-3 request-side">
<% if current_user.worker_profile %>
      <%= link_to "Back to Dashboard", dashboard_workers_path %>

<% end %>
      <h3> Price per hour:</h3><h2 style="margin-bottom: 10px;">€<%= @worker_profile.price_per_hour %></h2>
      <%#= link_to "Book", root_path, class: "btn-medium" %>
      <% if current_user.owner_profile %>

        <% if @job %>
        <%= simple_form_for @request do |f| %>
          <%= f.hidden_field :worker_profile_id, value: @worker_profile.id %>
          <%= f.hidden_field :job_id, value: @job.id %>
          <%= f.hidden_field :category, value: @worker_profile.skill_area %>
          <%= f.submit "Send Request for #{@job.title}", class: "btn btn-primary" %>
        <% end %>
      <% end %>

      <% end %>

    </div>
  </div>
</div>